docs: fix syntax error for pre-script.rhai example (#1479)
fix syntax error for pre-script.rhai example

Error: ⛔   Failed executing script: pre-script.rhai

Caused by:
Syntax error: Expecting ';' to terminate this statement (line 4,
position 1)