fix(ci): relax the force rule for audit, because of this report
error: Vulnerable crates found!

ID:       RUSTSEC-2020-0041
Crate:    sized-chunks
Version:  0.6.2
Date:     2020-09-06
URL:      https://rustsec.org/advisories/RUSTSEC-2020-0041
Title:    Multiple soundness issues in Chunk and InlineArray
Solution:  No safe upgrade is available!
Dependency tree:
sized-chunks 0.6.2
└── im-rc 15.0.0
    └── cargo 0.50.0
        └── cargo-generate 0.5.1

warning: 1 warning found

Crate:  difference
Title:  difference is unmaintained
Date:   2020-12-20
URL:    https://rustsec.org/advisories/RUSTSEC-2020-0095
Dependency tree:
difference 2.0.0
└── predicates 1.0.6
    ├── cargo-generate 0.5.1
    └── assert_cmd 1.0.2
        └── cargo-generate 0.5.1

error: 1 vulnerability found!
warning: 1 warning found!