fix: missing `.liquid` stripping in git templates (#1480)
Caused by a regression in
https://github.com/cargo-generate/cargo-generate/commit/a0dba72622b1ba903e0e7e484741d4380e303cf9.

```
(HEAD detached at a0dba72) $ ./target/debug/cargo-generate generate gibbz00/basic-things
⚠️   Favorite `gibbz00/basic-things` not found in config, using it as a git repository: https://github.com/gibbz00/basic-things.git
🤷   Project Name: test123
🔧   Destination: /tmp/test123 ...
🔧   project-name: test123 ...
🔧   Generating template ...
Error: ⛔   Failed executing script: cargo_generate/script.rhai

Caused by:
    Runtime error: No such file or directory (os error 2)
```

From the commit before:

```
(HEAD detached at ea23bab) $ ./target/debug/cargo-generate generate gibbz00/basic-things
⚠️   Favorite `gibbz00/basic-things` not found in config, using it as a git repository: https://github.com/gibbz00/basic-things.git
🤷   Project Name: test123
🔧   Destination: /tmp/test123 ...
🔧   project-name: test123 ...
🔧   Generating template ...
🤷   Repository path (usually 'username/repository_name'): 
```