fix: fix syntax error
fix:
Error: ⛔   Failed executing script: pre-script.rhai

Caused by:
    Syntax error: Expecting ';' to terminate this statement (line 4, position 1)