feat: enhance invalid identiy file error message (#595)
`canonicalize_path` will return an error if the constructed path does not exist,
because this is what `Path::canonicalize` does. However, in many places the use of `?`
short circuits the error return preventing the sometimes redundant
`path.exists()` check from running on the next line and bailing with the actual
path. This small change ensures that the path always gets printed when it does not exist.

Additionally, since this error occurs when `$HOME/.ssh/id_rsa` is not found, the user
is now made aware that the program is looking for this file. To help rectify this a help
message is appended in this situation.

Before:
```
cargo-generate git:(main) cargo generate --git git@github.com:xxx/xxx --name yyy
⚠️   Unable to load config file: /Users/ajs/.cargo/cargo-generate.toml
Error: ⛔   Git Error: path does not exist
```

After:
```
cargo-generate git:(main) cargo generate --git git@github.com:xxx/xxx --name yyy
⚠️   Unable to load config file: /Users/ajs/.cargo/cargo-generate.toml
Error: ⛔   Git Error: path does not exist: /Users/ajs/.ssh/id_rsa
help: try using the '--identity' flag
```